<?php
return array (
  'ckm3u8' => 
  array (
    'status' => '1',
    'from' => 'ckm3u8',
    'show' => '线路一',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99999',
    'tip' => '',
    'id' => 'ckm3u8',
  ),
  'wlm3u8' => 
  array (
    'status' => '1',
    'from' => 'wlm3u8',
    'show' => '线路二',
    'des' => 'https://wlzy.tv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99998',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'wlm3u8',
  ),
  'zuidam3u8' => 
  array (
    'status' => '1',
    'from' => 'zuidam3u8',
    'show' => '线路三',
    'des' => 'http://www.zuidazy.net/',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://zuidajiexi.net/m3u8.html?url=',
    'sort' => '99997',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zuidam3u8',
  ),
  '123kum3u8' => 
  array (
    'status' => '1',
    'from' => '123kum3u8',
    'show' => '线路四',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://jx.123ku.com/123kudpbfq/?url=',
    'sort' => '99996',
    'tip' => '',
    'id' => '123kum3u8',
  ),
  'kkm3u8' => 
  array (
    'status' => '1',
    'from' => 'kkm3u8',
    'show' => '线路五',
    'des' => 'http://www.kuyunzy.cc',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://www.kuyunjiexi.com/?url=',
    'sort' => '99994',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'kkm3u8',
  ),
  '158m3u8' => 
  array (
    'status' => '1',
    'from' => '158m3u8',
    'show' => '线路六',
    'des' => '158资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://www.hnyzyzs.com/158zyzdpbfq/?url=',
    'sort' => '99993',
    'tip' => '',
    'id' => '158m3u8',
  ),
  'kuyun' => 
  array (
    'status' => '1',
    'from' => 'kuyun',
    'show' => '线路七',
    'des' => 'http://okzyw.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '9999',
    'tip' => '来源：OK资源',
    'id' => 'kuyun',
  ),
  'yuku' => 
  array (
    'status' => '1',
    'from' => 'yuku',
    'show' => '优酷',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '2222',
    'tip' => '',
    'id' => 'yuku',
  ),
  'tudou' => 
  array (
    'status' => '1',
    'from' => 'tudou',
    'show' => '土豆',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '2221',
    'tip' => '',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '爱奇艺',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1112',
    'tip' => '',
  ),
  '123kuyun' => 
  array (
    'status' => '1',
    'from' => '123kuyun',
    'show' => '线路八',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '1000',
    'tip' => '',
    'id' => '123kuyun',
  ),
  'mgm3u8' => 
  array (
    'status' => '1',
    'from' => 'mgm3u8',
    'show' => '线路十',
    'des' => 'http://mgtvzy.com/',
    'target' => '_self',
    'ps' => '0',
    'parse' => 'https://shijim3u8.com/dp/?url=',
    'sort' => '999',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'mgm3u8',
  ),
  'dplayer' => 
  array (
    'status' => '1',
    'from' => 'dplayer',
    'show' => 'DPlayer-H5播放器',
    'des' => 'dplayer.js.org',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '908',
    'tip' => '无需安装任何插件',
    'id' => 'dplayer',
  ),
  'videojs' => 
  array (
    'status' => '1',
    'sort' => '907',
    'from' => 'videojs',
    'show' => 'videojs-H5播放器',
    'des' => 'videojs.com',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'videojs',
  ),
  'iva' => 
  array (
    'status' => '1',
    'from' => 'iva',
    'show' => 'iva-H5播放器',
    'des' => 'videojj.com',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '906',
    'tip' => '无需安装任何插件',
    'id' => 'iva',
  ),
  'iframe' => 
  array (
    'status' => '1',
    'from' => 'iframe',
    'show' => 'iframe外链数据',
    'des' => 'iframe外链数据',
    'ps' => '0',
    'parse' => '',
    'sort' => '905',
    'tip' => '无需安装任何插件',
    'id' => 'iframe',
  ),
  'link' => 
  array (
    'status' => '1',
    'sort' => '904',
    'from' => 'link',
    'show' => '外链数据',
    'des' => '外部网站播放链接',
    'ps' => '0',
    'parse' => '',
    'tip' => '无需安装任何插件',
    'id' => 'link',
  ),
  'swf' => 
  array (
    'status' => '1',
    'sort' => '903',
    'from' => 'swf',
    'show' => 'Flash文件',
    'des' => 'swf',
    'parse' => '',
    'ps' => '0',
    'tip' => '无需安装任何插件',
    'id' => 'swf',
  ),
  'flv' => 
  array (
    'status' => '1',
    'from' => 'flv',
    'show' => 'Flv文件',
    'des' => 'flv',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '902',
    'tip' => '无需安装任何插件	',
    'id' => 'flv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'pptv',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '123',
    'tip' => '',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '111',
    'tip' => '',
  ),
  'kkyun' => 
  array (
    'status' => '1',
    'from' => 'kkyun',
    'show' => '线路九',
    'des' => 'http://www.kuyunzy.cc',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'kkyun',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '线路十四',
    'des' => 'http://mgtvzy.com/',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'mgtv',
  ),
  'wlzy' => 
  array (
    'status' => '1',
    'from' => 'wlzy',
    'show' => '线路十一',
    'des' => 'http://wlzy.tv',
    'target' => '_self',
    'ps' => '1',
    'parse' => 'https://jx.wlzy.tv/jx.php?url=',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'wlzy',
  ),
  'zuidall' => 
  array (
    'status' => '1',
    'from' => 'zuidall',
    'show' => '线路十三',
    'des' => 'http://www.zuidazy.net/',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '99',
    'tip' => '在线播放,无需安装播放器',
    'id' => 'zuidall',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '22',
    'tip' => '',
  ),
  '158yun' => 
  array (
    'status' => '1',
    'from' => '158yun',
    'show' => '线路十二',
    'des' => '158资源',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '6',
    'tip' => '',
    'id' => '158yun',
  ),
  'ku6' => 
  array (
    'status' => '1',
    'from' => 'ku6',
    'show' => 'ku6',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '2',
    'tip' => '',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐',
    'des' => '',
    'target' => '_self',
    'ps' => '0',
    'parse' => '',
    'sort' => '',
    'tip' => '',
  ),
);